"""Init 4-tuple Quad-Store architecture

Revision ID: 90be5a38f8bf
Revises: 
Create Date: 2026-04-02 19:09:46.836169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90be5a38f8bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_correlation_id'), 'event_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_table('named_graphs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_entity_id', sa.String(), nullable=True),
    sa.Column('object_literal_value', sa.String(), nullable=True),
    sa.Column('graph_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_correlation_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(object_entity_id IS NULL AND object_literal_value IS NOT NULL) OR (object_entity_id IS NOT NULL AND object_literal_value IS NULL)', name='check_exclusive_object'),
    sa.ForeignKeyConstraint(['graph_id'], ['named_graphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quads_gpso', 'quads', ['graph_id', 'predicate', 'subject_id', 'object_entity_id'], unique=False)
    op.create_index('idx_quads_pogs', 'quads', ['predicate', 'object_entity_id', 'graph_id', 'subject_id'], unique=False)
    op.create_index('idx_quads_spog', 'quads', ['subject_id', 'predicate', 'object_entity_id', 'graph_id'], unique=False)
    op.create_index(op.f('ix_quads_graph_id'), 'quads', ['graph_id'], unique=False)
    op.create_index(op.f('ix_quads_predicate'), 'quads', ['predicate'], unique=False)
    op.create_index(op.f('ix_quads_source_correlation_id'), 'quads', ['source_correlation_id'], unique=False)
    op.create_index(op.f('ix_quads_subject_id'), 'quads', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quads_subject_id'), table_name='quads')
    op.drop_index(op.f('ix_quads_source_correlation_id'), table_name='quads')
    op.drop_index(op.f('ix_quads_predicate'), table_name='quads')
    op.drop_index(op.f('ix_quads_graph_id'), table_name='quads')
    op.drop_index('idx_quads_spog', table_name='quads')
    op.drop_index('idx_quads_pogs', table_name='quads')
    op.drop_index('idx_quads_gpso', table_name='quads')
    op.drop_table('quads')
    op.drop_table('named_graphs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_correlation_id'), table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
