# apps/inspector/src/inspector/config.yaml
admin_username: "admin"
admin_password: "admin"
components_to_monitor:
  interface: "http://localhost:8000/inspector"
  store: "http://localhost:8001/inspector"
  controller: "http://localhost:8002/inspector"
  actor: "http://localhost:8003/inspector"
  memory: "http://localhost:8004/inspector"
  configurator: "http://localhost:8005/inspector"
