global:
  rabbitmq_url: "amqp://guest:guest@localhost:5672/"
  database_url: "postgresql+asyncpg://ana_admin:ana_password@localhost:5432/ana"
component_configs:
  interface: "interface.yaml"
  actor: "actor.yaml"
  controller: "controller.yaml"
  memory: "memory.yaml"
  store: "store.yaml"
  inspector: "inspector.yaml"
