# src/agents/domain_agents.py
import json
from typing import Annotated

from faststream import Context
from faststream.rabbit import RabbitRouter, RabbitQueue
from faststream.exceptions import RejectMessage

from ana.adapters.faststream_bus import events_exchange
from ana.domain.messages import (
    ResourceCreatedEvent,
    KnowledgeUpdatedEvent,
    MessageHeader,
)
from ana.domain.tuples import SPOCTuple
from ana.ports.interfaces import (
    ResourceRepositoryPort,
    KnowledgeGraphPort,
    MessageBusPort,
)

domain_router = RabbitRouter()

# Define the queues. The Reasoner uses a wildcard '#' to catch all knowledge updates.
processor_queue = RabbitQueue(
    "ana.queue.processors", routing_key="event.resource.created"
)
reasoner_queue = RabbitQueue(
    "ana.queue.reasoners", routing_key="event.knowledge.updated.#"
)


@domain_router.subscriber(queue=processor_queue, exchange=events_exchange)
async def handle_resource_created(
    event: ResourceCreatedEvent,
    repository: Annotated[ResourceRepositoryPort, Context("repository")],
    graph: Annotated[KnowledgeGraphPort, Context("graph")],
    bus: Annotated[MessageBusPort, Context("bus")],
):
    """Parses raw data, creates 4-tuples, writes to the graph, and emits a Knowledge event."""
    try:
        # 1. Fetch the raw data from the repository using the URI
        raw_data = await repository.fetch(event.resource_uri)
        parsed_data = json.loads(raw_data)

        # 2. Apply deterministic transformation to a SPOCTuple
        # For this example, we extract the 'status' from the JSON payload
        status_value = parsed_data.get("status", "unknown")

        new_tuple = SPOCTuple(
            subject=event.header.source_component,
            predicate="produced_data_status",
            object_=status_value,
            context="processor_ingestion",
        )

        # 3. Idempotently write to the Knowledge Graph
        await graph.merge_tuples([new_tuple])

        # 4. Emit the KnowledgeUpdatedEvent
        k_event = KnowledgeUpdatedEvent(
            header=MessageHeader(
                correlation_id=event.header.correlation_id,
                source_component="ProcessorNode",
            ),
            subgraph_id="processor_ingestion",
            tuple_count=1,
        )
        await bus.publish_event(
            routing_key="event.knowledge.updated.processor", event=k_event
        )

    except Exception as e:
        # Explicit NACK on unexpected failure
        raise RejectMessage() from e


@domain_router.subscriber(queue=reasoner_queue, exchange=events_exchange)
async def handle_knowledge_updated(
    event: KnowledgeUpdatedEvent,
    graph: Annotated[KnowledgeGraphPort, Context("graph")],
    bus: Annotated[MessageBusPort, Context("bus")],
):
    """Queries the graph, runs deterministic rules, deduces new tuples, and updates the graph."""
    try:
        # Prevent infinite reasoning loops: ignore events generated by this specific reasoner
        if event.reasoner_id == "RuleBasedReasoner":
            return

        # 1. Query the graph for specific patterns (e.g., nodes that produced 'success' status)
        query_string = """
            select SPOCTuple { subject, object_ }
            filter .predicate = 'produced_data_status' and .object_ = 'success';
        """
        results = await graph.query(query_string, {})

        # 2. Run deterministic rule-based deductions (No LLMs)
        new_tuples = []
        for res in results:
            # Rule: If a component produces a 'success' status, we deduce it is 'reliable'
            deduced_tuple = SPOCTuple(
                subject=res["subject"],
                predicate="is_state",
                object_="reliable",
                context="reasoner_deduction",
            )
            new_tuples.append(deduced_tuple)

        # 3. Write deduced tuples back to the graph
        if new_tuples:
            await graph.merge_tuples(new_tuples)

            # 4. Emit a new KnowledgeUpdatedEvent signaling the deduction
            k_event = KnowledgeUpdatedEvent(
                header=MessageHeader(
                    correlation_id=event.header.correlation_id,
                    source_component="RuleBasedReasoner",
                ),
                subgraph_id="reasoner_deduction",
                reasoner_id="RuleBasedReasoner",
                tuple_count=len(new_tuples),
            )
            await bus.publish_event(
                routing_key="event.knowledge.updated.reasoner", event=k_event
            )

    except Exception as e:
        raise RejectMessage() from e
