event_sources:
  ScrapingEventSource:
    enabled: true
    interval_minutes: 10
    store_api_url: "http://localhost:8001/files"
    targets:
      - url: "https://www.adnsur.com.ar/"
        backend: "httpx"
      - url: "https://www.diariojornada.com.ar/home"
        backend: "httpx"
      - url: "https://www.elchubut.com.ar/seccion/comodoro-rivadavia"
        backend: "httpx"
      - url: "https://www.diariocronica.com.ar/"
        backend: "httpx"
      # You can add a selenium target here when you want to test it:
      # - url: "https://en.wikipedia.org/wiki/Main_Page"
      #   backend: "selenium"

  RSSEventSource:
    enabled: true
    interval_minutes: 60
    store_api_url: "http://localhost:8001/files"
    targets:
      - "https://www.clarin.com/rss/lo-ultimo/"
      - "https://www.clarin.com/rss/politica/"
      - "https://www.clarin.com/rss/economia/"
      - "https://feeds.bbci.co.uk/news/rss.xml"
      - "https://hnrss.org/frontpage"

event_handlers:
  ProxyActionHandler:
    enabled: true
    proxy_url: "http://localhost:3000/webhook"
